### ISSUE TITLE
Create data extraction script for MT work and put in github repo.

### ISSUE THREAD

**Issue by RavneetDTU** [cdli-gh/Unsupervised-NMT-for-Sumerian-English#1]
To make the data more accessible to anyone wanting to experiment, we need a python script to extract the appropriate data from our datasets which are freely accessible online.
The data is here: https://github.com/cdli-gh/data
in the atf data file, each text starts with &P and end where the other text starts or with the end of the file. Check the texts one by one to see what their language is, if Sumerian, then extracts the text.
To select only text with translation, also check if #tr.en: is present in the text.
To select only a genre, cross-reference with the catalogue file and see look up the genre. The key between each file is the P number, in the text, it is the number following &P and in the catalogue it is in the field text_id.
The datasets to create should be :
All Sumerian (translated or not )
All Sumerian with parallel translation

**Comment by RachitBansal** [comment]
Hey, 
A script for this task had been created a couple of days ago and is present at [data extractor](https://github.com/cdli-gh/cdli-data-extractor). 

Should further developments for data extraction be done in that repository itself?

**Comment by Shashankjain12** [comment]
hello @RavneetDTU  I had created a PR with the following changes by adding the extract.py to the repository for data access kindly merge this PR
