### ISSUE TITLE
Cleaning the Raw extratced Data.

### ISSUE THREAD

**Issue by RavneetDTU** [cdli-gh/Unsupervised-NMT-for-Sumerian-English#4]
Files "sumerian_translated.atf" and "sumerian_untranslated.atf" are completlt Raw.
Make clean .txt files similar like in the dataset folder.

**Comment by Shashankjain12** [comment]
What do you mean by cleaning those files @RavneetDTU ? 
What characters do we need to remove from that files?

**Comment by RavneetDTU** [comment]
@Shashankjain12 Please look at the Sumerian text files in the Dataset folder.

**Comment by RachitBansal** [comment]
@RavneetDTU Considering the presence of monolingual data this time, should we keep the following files inside the `cleaned_data` folder: 

- `sumerian_mono.txt`
- `english_mono.txt`
- `sumerian_pll.txt`
- `english_pll.txt`

With necessary train, test and validation ones.

Also, are we supposed to use the same parallel data as last year?

**Comment by Rutvik-Trivedi** [comment]
@RavneetDTU just a small query, is it necessary to implement the data cleaner script without using a third party library, pandas for instance using only in-built python libs or is it fine to use a third party lib?

**Comment by TripleR47** [comment]
Script for cleaning the raw data added #8
